---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - remedy.io
  resources:
  - playbooks
  - remediationpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - remedy.io
  resources:
  - playbooks/finalizers
  - remediationpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - remedy.io
  resources:
  - playbooks/status
  - remediationpolicies/status
  verbs:
  - get
  - patch
  - update
