apiVersion: remedy.io/v1alpha1
kind: RemediationPolicy
metadata:
  labels:
    app.kubernetes.io/name: k8s-remedy-operator
    app.kubernetes.io/managed-by: kustomize
  name: remediationpolicy-sample
spec:
  # TODO(user): Add fields here
